// Compiles the whole portfolio into one plain-text document that the chat
// assistant gets as its knowledge base. Runs in "prebuild" (see package.json).
// Source of truth: supabase/functions/mcp/portfolio-data.ts + testimonialsData.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  about,
  academicProjects,
  certificateCategories,
  competitions,
  education,
  hackathonProjects,
  honours,
  minorExperiences,
  otherExperiences,
  portfolioProjects,
  profile,
  professionalExperiences,
  volunteering,
} from "../supabase/functions/mcp/portfolio-data.ts";
import { testimonials } from "../src/data/testimonialsData.ts";

const lines: string[] = [];
const h = (t: string) => lines.push("", `## ${t}`, "");
const bullet = (t: string) => lines.push(`- ${t}`);

lines.push("# Krithik Sharan S A - portfolio knowledge base");
lines.push("");
lines.push(`Headline: ${profile.headline}`);
lines.push(`Location: ${profile.location}`);
lines.push(`Current roles: ${profile.currentRoles.join("; ")}`);
lines.push(
  `Links - website ${profile.links.website}, email ${profile.links.email}, LinkedIn ${profile.links.linkedin}, GitHub ${profile.links.github}`,
);

h("About");
lines.push(about);

const expBlock = (title: string, list: typeof professionalExperiences) => {
  h(title);
  for (const e of list) {
    lines.push(`### ${e.role} - ${e.company} (${e.duration})`);
    if (e.description) lines.push(e.description);
    for (const a of e.achievements ?? []) bullet(a);
    lines.push("");
  }
};
expBlock("Work experience", professionalExperiences);
expBlock("Other experience (freelance, student leadership, internships)", otherExperiences);
expBlock("Earlier / school leadership", minorExperiences);

h("Education");
for (const ed of education) {
  lines.push(`### ${ed.degree} - ${ed.institution}, ${ed.location} (${ed.duration}) - ${ed.grade}`);
  if ("coreModules" in ed && ed.coreModules) lines.push(`Core modules: ${ed.coreModules.join(", ")}`);
  if ("electiveModules" in ed && ed.electiveModules) lines.push(`Electives: ${ed.electiveModules.join(", ")}`);
  lines.push("");
}

h("Academic projects");
for (const p of academicProjects) {
  lines.push(`### ${p.title} (${p.tag}) - ${p.subtitle}`);
  if (p.overview) lines.push(p.overview);
  if (p.methods?.length) lines.push(`Methods: ${p.methods.join("; ")}`);
  if (p.tools?.length) lines.push(`Tools: ${p.tools.join(", ")}`);
  if (p.results?.length) p.results.forEach(bullet);
  lines.push(`GitHub: ${p.githubUrl}`);
  lines.push("");
}

h("Portfolio / professional projects");
for (const p of portfolioProjects) {
  lines.push(`### ${p.title}`);
  lines.push(p.description);
  if (p.tools?.length) lines.push(`Tools: ${p.tools.join(", ")}`);
  lines.push(`GitHub: ${p.githubUrl}`);
  lines.push("");
}

h("Hackathon projects");
for (const p of hackathonProjects) {
  const result = "result" in p && p.result ? ` - ${p.result}` : "";
  lines.push(`### ${p.title}${result}`);
  lines.push(p.description);
  if ("tools" in p && p.tools?.length) lines.push(`Tech: ${p.tools.join(", ")}`);
  if ("githubUrl" in p && p.githubUrl) lines.push(`GitHub: ${p.githubUrl}`);
  if ("liveUrl" in p && p.liveUrl) lines.push(`Live: ${p.liveUrl}`);
  lines.push("");
}

h("Competitions");
for (const c of competitions) {
  lines.push(`### ${c.title} - ${c.position} (${c.issuer}, ${c.date})`);
  lines.push(c.summary);
  for (const hi of c.highlights ?? []) bullet(hi);
  lines.push("");
}

h("Honours & awards");
for (const a of honours) {
  lines.push(`### ${a.title} - ${a.issuer}, ${a.date}`);
  if (a.description) lines.push(a.description);
  lines.push("");
}

h("Certifications");
for (const cat of certificateCategories) {
  lines.push(`### ${cat.name}`);
  for (const c of cat.certificates) bullet(`${c.title} - ${c.issuer} (${c.date})`);
  lines.push("");
}

h("Volunteering");
for (const v of volunteering) {
  lines.push(`### ${v.role} - ${v.company} (${v.duration})`);
  if (v.description) lines.push(v.description);
  for (const a of v.achievements ?? []) bullet(a);
  lines.push("");
}

h("What people say (recommendations)");
for (const t of testimonials) {
  lines.push(`### ${t.name} - ${t.role}`);
  lines.push(t.full);
  lines.push("");
}

const context = lines.join("\n").replace(/\n{3,}/g, "\n\n").trim() + "\n";

const out = `// AUTO-GENERATED by scripts/generate-chat-context.mts - do not edit.
// Regenerated on every build from the portfolio data.
export const PORTFOLIO_CONTEXT = ${JSON.stringify(context)};
`;

const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(resolve(here, "../api/portfolio-context.ts"), out);
console.log(`portfolio-context.ts written (${context.length} chars, ~${Math.round(context.length / 4)} tokens)`);
