// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Krithik Sharan S A's profile summary: headline, current focus, contact links and portfolio site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Krithik Sharan S A",
      headline: "A Data Analyst who transforms numbers into narratives.",
      location: "Leeds, England",
      currentRoles: [
        "AI Automation Engineer at INOOKEY (Birmingham, UK)",
        "PGT Faculty Officer at The University of Leeds",
        "MSc Data Science and Analytics student, University of Leeds"
      ],
      links: {
        website: "https://krithik-sharan-portfolio-website.lovable.app",
        email: "krithiksharan13@gmail.com",
        linkedin: "https://www.linkedin.com/in/krithiksharan",
        github: "https://github.com/krithiksharan13"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/data/professionalExperience.ts
var professionalExperiences = [
  {
    role: "AI Automation Engineer",
    company: "INOOKEY - Birmingham, United Kingdom",
    duration: "November 2025 - Present",
    description: "Working with N8N automations and workflows based on client requirements.",
    achievements: [
      "Working with N8N automations and workflows based on client requirements",
      "Automated 2 client-facing workflows using n8n, resulting in a 30% reduction in manual effort and 25% faster process turnaround.",
      "Identified 8+ critical business and technical weak spots by developing a Business Risk & Loophole Assessment Report for a major project, improving overall risk visibility.",
      "Conducted competitor market analysis across ~10 competitors, uncovering 3+ market gaps and proposing 2 strategic recommendations to support product positioning."
    ]
  },
  {
    role: "Data Analyst-BI Developer",
    company: "Radiant Ventures",
    duration: "November 2024 - September 2025",
    description: "Worked as a investment risk professional who reduced client losses by 25% through data-driven A/B testing and comprehensive portfolio analysis. I specialized in cross-functional collaboration to optimize workflows, cutting redundancy by 40% and aligning risk strategy with business growth.",
    achievements: [
      "Designed and executed A/B tests on risk communication involving over 250 users and \u20B930+ Lakh in investments, resulting in a 25% reduction in investment losses and increased preference for low-risk products.",
      "Conducted portfolio audits and flagged anomalies for 15+ clients; completed over 100 investment risk assessments to support informed financial decision-making.",
      "Collaborated with Sales, Product, and Compliance teams to identify and resolve operational inefficiencies, reducing workflow redundancy by 40% and improving team throughput by 10%.",
      "Took on cross-functional responsibilities across data, business, and risk domains, contributing insights that influenced product strategy, compliance, and investment design that reduced overall losses by 5%.",
      "Analyzed risk profiles for 100+ investment opportunities, accelerating the team's decision-making process by 10%.",
      "Migrated investment data from physical formats to digital systems, significantly improving data accessibility and management.",
      "Designed and delivered 10+ reports and interactive dashboards, contributing to a 15% reduction in turnaround time for investment reviews.",
      "Collaborated cross-functionally with investment teams to align risk insights with business goals and ensure scalable, informed growth strategies."
    ]
  },
  {
    role: "Data Analyst Intern",
    company: "Unified Mentor",
    duration: "January 2024 - June 2024",
    description: "Led exploratory data analysis that improved trend detection by 10%, built dashboards enhancing insight delivery by 15%, and contributed ideas that accelerated decisions by 20% and cut errors by 5%.",
    achievements: [
      "Spearheaded exploratory data analysis efforts, which directly contributed to a noticeable 10% increase in identifying revenue-generating trends, patterns, and anomalies within datasets.",
      "Skillfully crafted and implemented visualizations, reports, and dashboards, resulting in a 15% improvement in effectively communicating actionable insights to stakeholders.",
      "Actively Collaborated in meetings and brainstorming sessions, offering innovative ideas that led to 20% faster decision-making processes and a notable 5% reduction in error margin."
    ]
  },
  {
    role: "Junior Data Analyst Intern",
    company: "Shopup",
    duration: "2022 - 2023",
    description: "Assisted in data collection, cleaning, and preliminary analysis. Developed skills in SQL, Python, and data visualization tools.",
    achievements: [
      "Provided 50+ reports to the stakeholders and finance team for the yearly audit using SQL, BigQuery and metabase.",
      "Used python to generate reports and extract data from metabase, attach it to emails and send them to the 8+ departments.",
      "Increased efficiency by 20% in data extraction by utilizing SQL queries for retrieving relevant information from databases.",
      "Created documentation and provided updated nearly 500+ reports that ensured proper function and decreased cost of execution by 5%.",
      'Worked on the basics of a portal for the users and stakeholders called "infinity portal" using GoLang (internship project).'
    ]
  }
];

// src/data/minorExperience.ts
var minorExperiences = [
  {
    role: "Achievers House Captain",
    company: "Pushpalatha Vidya Mandir",
    duration: "June 2017 - February 2018",
    description: "Led the Achiever's House (Blue Team) to a Second Place Finish in the Inter-House Competitions.",
    achievements: [
      "Won the Overall Male Individual Champion in the Super Senior Category.",
      "Won Gold medals in Shotput, Discus Throw and Javelin throw in the Super Senior Sports Meet 2017-2018.",
      "International English Olympiad - International Rank: 134",
      "International Mathematics Olympiad - State Rank: 24",
      "International Science Olympiad - State Rank: 54",
      "Won an Award for being a member of the best football team at Pushplatha Group of Schools for the performance from 2014-2018"
    ]
  },
  {
    role: "Under-19 Football Team Captain",
    company: "Pushpalatha Vidya Mandir",
    duration: "2016-2017",
    description: "Led the School's Football Team in the Under-19 Age Category and Won the first Place in the South Tamil Nadu Cluster Matches.",
    achievements: [
      "Won the Award for the best defender of the tournament.",
      "Won and award for 100% penalty goal conversion.",
      "Won the Gold Medal for the 2nd year in a row.",
      "Won the first place in the Inter School Matches in the Tirunelveli District for 3 Consecutive years."
    ]
  },
  {
    role: "Achievers Sports Captain",
    company: "Pushpalatha Vidya Mandir",
    duration: "June 2016 - February 2017",
    description: "Led the Achiever's House (Blue Team) to a Second Place Finish in the Inter-House Sports Competitions.",
    achievements: [
      "Won Silver medals in Shotput and Bronze medal in Discus Throw in the Super Senior Sports Meet 2016-2017.",
      "Won the Inter House Volleyball Matches for the Super Senior Category.",
      "Won the Inter House Basketball Matches for the Super Senior Category.",
      "Trained the Junior Under-16 Football team that won the Gold Medal in the Under-16 Category.",
      "International English Olympiad - State Rank: 29"
    ]
  },
  {
    role: "Under-19 Basketball Team Captain",
    company: "Pushpalatha Vidya Mandir",
    duration: "2016-2017",
    description: "Led the School's First Ever Basketball Team in the Under-19 Age Category and place in top 6 of the South Tamil Nadu Cluster.",
    achievements: [
      "Placed in the 5th Position in the Under-19 Age Category.",
      "Won the Inter School Matches held in the Tirunelveli District."
    ]
  },
  {
    role: "Under-16 Football Team Captain",
    company: "Pushpalatha Vidya Mandir",
    duration: "2014-2016",
    description: "Led the School's First Ever Football Team in the Under-16 Age Category and created a historic run of not conceding a single goal in the Under-16 Category for the year 2015-2016.",
    achievements: [
      "Won the Award for the best defender of the tournament.",
      "Won and award for most penalty to goal conversion.",
      "Won the Gold Medal in the 2015-2016 year South Tamil Nadu Cluster Matches.",
      "Won the Silver Medal in the 2014-2015 year South Tamil Nadu Cluster Matches.",
      "Won the first place in the Inter School Matches in the Tirunelveli District for two Consecutive years(2014-2016)."
    ]
  },
  {
    role: "Other Responsibilities",
    company: "Pushpalatha Vidya Mandir",
    duration: "",
    description: "",
    achievements: [
      "10th Grade English Club President",
      "9th Grade Environmental Club Secretary",
      "10th Grade Junior Sports Captain for the Achiever's House(Blue)."
    ]
  }
];

// src/data/otherExperience.ts
var otherExperiences = [
  {
    role: "Post Graduate(Taught) Faculty Officer",
    company: "The University of Leeds - Leeds University Union",
    duration: "November 2025 - present",
    description: "Selected as the Faculty Officer Representing all the Engineering and Physical Sciences Departments.",
    achievements: [
      "Created and launched the official EPS Student Community Instagram, establishing a single faculty-wide communication channel that supports 100+ EPS students and improves reach, awareness, and engagement across all schools.",
      "Represented EPS PGT students in quality assurance, international student life, and inter-school communication initiatives, collecting, synthesising, and escalating student feedback to influence faculty-level discussions and student experience improvements.",
      "Actively participated in FTSEC meetings, formally presenting student concerns and insights, and ensuring PGT perspectives were reflected in faculty decisions, policy discussions, and cross-school coordination."
    ]
  },
  {
    role: "Freelance UI Designer",
    company: "Org Linked",
    duration: "December 2024",
    description: "Helped design the User Interface of the first version of their Official Website using Figma.",
    achievements: [
      "Designed and developed a custom user interface tailored to specific client requirements, ensuring a seamless and intuitive user experience across platforms.",
      "Collaborated closely with stakeholders to translate complex requirements into a visually engaging and functional UI, contributing to a 25% boost in user satisfaction.",
      "Focused on clean, maintainable code and responsive design, enabling faster development cycles and improved cross-device compatibility."
    ]
  },
  {
    role: "Freelance Frontend Developer",
    company: "Barani TV",
    duration: "February 2023 - May 2023",
    description: "Developed the first version of the responsive website interface for Barani TV, a press and multimedia company based in Tirunelveli, Tamil Nadu, using TypeScript, Tailwind CSS, and HTML.",
    achievements: [
      "Developed 100% of the frontend using TypeScript (60%), Tailwind CSS (30%), and HTML (10%).",
      "Created modular, reusable UI components, reducing future development effort by 40%.",
      "Achieved 95%+ responsiveness and cross-browser compatibility across mobile, tablet, and desktop.",
      "Delivered a Google Lighthouse Performance Score of 90+, ensuring fast and optimized load times.",
      "Focused purely on interface development; backend, DBMS, and deployment were handled by separate teams."
    ]
  },
  {
    role: "Design and Marketing Head",
    company: "ProcodeIT",
    duration: "August 2021 - May 2022",
    description: "Streamlined the functioning of the dormant Department Coding Club by Organizing events, creating a social media presence, posting regular content.",
    companyLink: "https://www.instagram.com/procode_it_ssn/?hl=en",
    achievements: [
      "Taught the basics of Premier Pro to nearly 20+ students in a virtual setting.",
      "Created the Social Media presence of the Club.",
      "Helped in organizing nearly 10+ events.",
      "Created 40+ posters and 10+ invitations.",
      "Grew the Club from 20 members to one of 250+ members."
    ]
  },
  {
    role: "Information Technology Intern",
    company: "Ramco Cements Pvt Ltd.",
    duration: "January 2022 - February 2022",
    description: "Learnt the functioning of the company including the logistics behind it, helping the team in tasks involving documentation, integrity checking and Analysis assistance.",
    achievements: [
      "Delivered assistance and support for team-based IT projects which improved efficiency by 10%.",
      "Completed 25+ assigned tasks ahead of schedule, demonstrating strong time management skills and commitment to project success.",
      "Developed comprehensive documentation for internal use, simplifying knowledge transfer among team members which reduced misinformation and errors in communication by 15%."
    ]
  },
  {
    role: "Video Editor & Media Coordinator",
    company: "TEDxYouth@Vannarpettai",
    duration: "December 2019 \u2013 May 2020",
    description: "Led video production, sponsor coordination, and live streaming for TEDxYouth@Vannarpettai - one of South Tamil Nadu's first TEDx events.",
    companyLink: "https://www.instagram.com/tedxyouthvannarpettai/?hl=en",
    achievements: [
      "Edited all event videos (talks, promos, sponsor reels), ensuring alignment with TEDx brand standards.",
      "Coordinated with 6+ speakers and team members to collect and finalize video content.",
      "Managed sponsor video integration and communication, securing high-quality ad placements.",
      "Organized and executed end-to-end live streaming on BigBlueButton for a smooth virtual event.",
      "Created social media clips and highlight reels, boosting local engagement and awareness.",
      "Provided real-time technical support during the event, minimizing disruptions.",
      "Played a key role in launching one of South Tamil Nadu's first TEDx events, earning TED approval."
    ]
  }
];

// src/lib/mcp/tools/list-experience.ts
var groups = {
  professional: professionalExperiences,
  minor: minorExperiences,
  other: otherExperiences
};
var list_experience_default = defineTool2({
  name: "list_experience",
  title: "List work experience",
  description: "List Krithik's work experience entries (role, company, duration, description, achievements). Optionally filter by category.",
  inputSchema: {
    category: z.enum(["professional", "minor", "other", "all"]).optional().describe("Which experience group to return. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const selected = !category || category === "all" ? ["professional", "minor", "other"] : [category];
    const result = selected.map((key) => ({ category: key, items: groups[key] }));
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { groups: result }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";

// src/data/projectsData.ts
var projects = [
  {
    title: "Blinkit Analysis SQL Project",
    description: "Analyzed Blinkit's sales, customer satisfaction, and inventory to extract actionable insights for optimization.",
    tools: ["SQL", "Exploratory Data Analysis"],
    imageUrl: "/lovable-uploads/5b762e4a-e89d-41da-a520-7c7eb6e00513.png",
    githubUrl: "https://github.com/krithiksharan13/BlinkIt-Analysis---SQL-Project.git"
  },
  {
    title: "A/B Testing Analysis: Mutual Fund Risk Label Impact",
    description: "Executed a comprehensive A/B testing workflow to assess the impact of visual risk labels on user behavior in mutual fund selection, comparing labeled vs unlabeled interfaces.",
    tools: ["A/B Testing", "Statistical Analysis", "Python", "Data Visualization"],
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    githubUrl: "https://github.com/krithiksharan13/A_B-Testing-Analysis-Mutual-Fund-Risk-Label-Impact.git"
  },
  {
    title: "Mutual Fund Risk Indicator",
    description: "Used machine learning to classify Indian mutual funds into risk categories based on historical performance.",
    tools: ["Python", "Machine Learning", "Streamlit"],
    imageUrl: "https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=800",
    githubUrl: "https://github.com/krithiksharan13/Mutual_Fund_Risk_Predictor.git"
  },
  {
    title: "FnP Sales Analysis",
    description: "Developed an Excel dashboard for Ferns and Petals to uncover insights on revenue, customers, and product performance.",
    tools: ["Excel", "DAX", "Data Visualization"],
    imageUrl: "/lovable-uploads/03acd844-096d-479f-9edd-1bf49048d3ae.png",
    githubUrl: "https://github.com/krithiksharan13/FnP-Sales-Analysis---Excel-Dashboard.git"
  },
  {
    title: "Quantium Data Analytics Virtual Experience",
    description: "Analyzed supermarket chip purchase data to understand customer behavior and evaluate a new store layout trial.",
    tools: ["Python", "Pandas", "Matplotlib", "PowerPoint"],
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
    githubUrl: "https://github.com/krithiksharan13/Quantium-Virtual-Internship.git"
  },
  {
    title: "Amazon Sales Data Dashboard",
    description: "An exploratory data analysis to understand sales trends, profitability, and regional performance on Amazon.",
    tools: ["Power BI", "Python", "Excel", "Jupyter Notebook"],
    imageUrl: "/lovable-uploads/baf94e99-6084-4f99-8ae3-63d198ec1784.png",
    githubUrl: "https://github.com/krithiksharan13/Unified_Mentor_Amazon_Sales_Dashboard.git"
  },
  {
    title: "BCG GenAI Job Simulation",
    description: "Built an AI-powered financial chatbot to interpret company performance from 10-K filings using NLP.",
    tools: ["Python", "Pandas", "NLP", "Jupyter Notebook", "Prompt Engineering"],
    imageUrl: "/lovable-uploads/cd51b6c9-9dd7-4b7a-837c-7416d989cd42.png",
    githubUrl: "https://github.com/krithiksharan13/BCG-GenAI-Job-Simulation-Forage.git"
  },
  {
    title: "Accenture Data Analytics & Visualization",
    description: "Applied data analytics and visualization to help a social media company improve its content creation strategy.",
    tools: ["Excel", "Data Cleaning", "Data Modeling", "Data Visualization"],
    imageUrl: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800",
    githubUrl: "https://github.com/krithiksharan13/Accenture-Data-Analytics-and-Visualization---Forage.git"
  },
  {
    title: "Heart Rate Diagnose Data Analysis",
    description: "Conducted analysis on medical data to explore and derive insights from patients with heart-related problems.",
    tools: ["Python", "Pandas", "Excel", "Tableau"],
    imageUrl: "/lovable-uploads/2f5c821f-1ac0-4c9a-90aa-7724525c0f46.png",
    githubUrl: "https://github.com/krithiksharan13/Unified_Mentor_Heart_Rate_Analysis.git"
  },
  {
    title: "British Airways Data Science Internship",
    description: "Analyzed customer reviews and built predictive models to forecast customer buying behavior for British Airways.",
    tools: ["Python", "Jupyter Notebook", "Pandas", "Scikit-learn"],
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800",
    githubUrl: "https://github.com/krithiksharan13/British-Airways-Data-Science---Forage.git"
  },
  {
    title: "TATA Data Visualization Internship",
    description: "Created Power BI dashboards analyzing retail sales data to support C-level decision-making.",
    tools: ["Power BI", "Data Analysis", "Business Strategy"],
    imageUrl: "/lovable-uploads/35dcf107-6ff2-41b9-834a-8638842c3393.png",
    githubUrl: "https://github.com/krithiksharan13/TCS-Virtual-Internship.git"
  },
  {
    title: "PwC Switzerland Power BI Experience",
    description: "Developed Power BI dashboards for call center, customer retention, and D&I to drive strategic business decisions.",
    tools: ["Power BI", "Trend Analysis", "Customer Churn Analysis"],
    imageUrl: "/lovable-uploads/977b9fd0-d68d-4444-93dc-b21e873ec0d3.png",
    githubUrl: "https://github.com/krithiksharan13/PwC-Switzerland-Power-BI.git"
  }
];

// src/data/hackathonProjectsData.ts
var hackathonProjects = [
  {
    title: "CheerpJ 2025",
    description: "This is a submission of CheerPJ Hackathon 2025. This project is a fully interactive GameBoy-style web console built using only HTML, CSS, and vanilla JavaScript. It is capable of running Java .jar games directly inside the browser using CheerpJ 3.0, without requiring any local Java installation. The UI simulates the classic handheld console, including a power button, LED indicator, startup animation, cartridge loading, and fully functional A/B, D-Pad, Start, and Select buttons. The project also includes a built-in game loader for .jar files.",
    githubUrl: "https://github.com/krithiksharan13/CheerPJ-2025",
    liveUrl: "https://cheer-pj-2025.vercel.app/",
    isWinner: true
  },
  {
    title: "AETHRA GLOBAL IDEATHON 2025: VoiceCity",
    description: "VoiceCity is our submission for the Aethra Global Ideathon 2025, a project dedicated to reimagining urban accessibility through community-driven data and AI-powered technology. We came in the finalist panels amidst 250+ submissions.",
    githubUrl: "https://github.com/krithiksharan13/AETHRA-GLOBAL-IDEATHON-2025",
    liveUrl: "https://aethra-global-ideathon-2025.onrender.com/",
    isWinner: true
  },
  {
    title: "Spooky Maze\u2014Escape the Alchemist's Study",
    description: "Our submission to the Horror Hacks Hackathon - A beginner friendly hackathon centered all about Halloween! Spooky Maze is an AI-powered, web-based, point-and-click puzzle horror game. We challenged ourselves to create a heart-pounding psychological experience using minimal design and eerie ambiance, all within a browser. The game tests a simple question: Can logic survive panic?",
    githubUrl: "https://github.com/krithiksharan13/Horror-Hacks-Hackathon-2025",
    liveUrl: "https://horror-hacks-hackathon-2025.onrender.com/",
    position: "Honorable Mention"
  },
  {
    title: "Polyglot Harmony AI Bot",
    description: "Our submission to the Hack4Unity Hackathon - A beginner friendly hackathon centered around creating an app or software that will create more unity between people! We came in 5th amidst 90+ Submissions. Polyglot Harmony AI Bot was created to help people communicate naturally, in their own voice, without linguistic friction. A tool that understands how we speak \u2014 not how a textbook expects us to.",
    githubUrl: "https://github.com/krithiksharan13/Hack4Unity-Polyglot-Harmony-AI-Bot",
    liveUrl: "https://polyglot-harmony-ai-bot.onrender.com/",
    position: "5th"
  },
  {
    title: "DevOne Hack",
    description: "This project was built and submitted as part of the DevOne Hack hackathon. This repository was created to push the project to GitHub for the hackathon submission. This repository contains the code and assets for my personal portfolio website, built to showcase my skills, experience, and projects.",
    githubUrl: "https://github.com/krithiksharan13/krithik-sharan-portfolio-website",
    liveUrl: "https://krithik-sharan-portfolio-website.lovable.app/"
  }
];

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List projects",
  description: "List Krithik's portfolio projects and hackathon projects, including tools used and repository or live links.",
  inputSchema: {
    category: z2.enum(["portfolio", "hackathon", "all"]).optional().describe("Which project group to return. Defaults to all."),
    search: z2.string().optional().describe("Case-insensitive text filter on title, description or tools.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, search }) => {
    const q = search?.trim().toLowerCase();
    const matches = (value) => !q || JSON.stringify(value).toLowerCase().includes(q);
    const portfolio = projects.filter(matches).map(({ title, description, tools, githubUrl }) => ({ title, description, tools, githubUrl }));
    const hackathon = hackathonProjects.filter(matches);
    const result = {
      portfolio: !category || category === "all" || category === "portfolio" ? portfolio : [],
      hackathon: !category || category === "all" || category === "hackathon" ? hackathon : []
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-certificates.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/certificatesList.ts
var certificateCategoriesInfo = [
  {
    name: "Data Analytics",
    emoji: "\u{1F4CA}",
    certificates: [
      {
        title: "Learning ChatGPT for Business Analysis",
        issuer: "LinkedIn Learning",
        date: "Feb 2026",
        credentialId: "c980b5a9af5a3bf960575b2a8f6d16b92beba28486d4709c06106636fdf174b0",
        url: "https://www.linkedin.com/learning/certificates/c980b5a9af5a3bf960575b2a8f6d16b92beba28486d4709c06106636fdf174b0"
      },
      {
        title: "Introduction to Web APIs",
        issuer: "LinkedIn Learning",
        date: "Jan 2026",
        credentialId: "01327d0af6d0fc52305231982697cec33e46c8d4baf19e873cf06c7892e8fe79",
        url: "https://www.linkedin.com/learning/certificates/01327d0af6d0fc52305231982697cec33e46c8d4baf19e873cf06c7892e8fe79"
      },
      {
        title: "Learning SQL Programming",
        issuer: "LinkedIn Learning",
        date: "Jan 2026",
        credentialId: "50b26602e2fc5c3da6d823caddd77636158986a6783742e4ad90fd7c1bc9f921",
        url: "https://www.linkedin.com/learning/certificates/50b26602e2fc5c3da6d823caddd77636158986a6783742e4ad90fd7c1bc9f921"
      },
      {
        title: "R for Data Science: Analysis and Visualization",
        issuer: "LinkedIn Learning",
        date: "Jan 2026",
        credentialId: "84de22107f4440021bca067a9232bcd4fa2b268d6462d0ac76d351f61d0316d5",
        url: "https://www.linkedin.com/learning/certificates/84de22107f4440021bca067a9232bcd4fa2b268d6462d0ac76d351f61d0316d5"
      },
      {
        title: "2025 Complete SQL Bootcamp from Zero to Hero in SQL",
        issuer: "Udemy",
        date: "May 2024",
        credentialId: "UC-dde71214-d932-41f4-a7f3-d69f67204e42"
      },
      {
        title: "Data Analyst Skillpath: Zero to Hero in Excel, SQL & Python",
        issuer: "Udemy",
        date: "Jul 2024",
        credentialId: "UC-5a72747f-fe9b-4ea0-9345-daae4c0ade51"
      }
    ]
  },
  {
    name: "AI",
    emoji: "\u{1F916}",
    certificates: [
      {
        title: "What is Generative AI",
        issuer: "LinkedIn Learning",
        date: "Feb 2026",
        credentialId: "202bb94a3aa0774ee71a506a8105a4cde867d0315f9486e841fdd561cd7007b1",
        url: "https://www.linkedin.com/learning/certificates/202bb94a3aa0774ee71a506a8105a4cde867d0315f9486e841fdd561cd7007b1"
      },
      {
        title: "Artificial Intelligence Creating Video From Photo",
        issuer: "Udemy",
        date: "Apr 2025",
        credentialId: "UC-b5959bc3-9c4f-45c5-b6fd-9afb222916eb"
      },
      {
        title: "Professional Logo Production With Artificial Intelligence",
        issuer: "Udemy",
        date: "Apr 2025",
        credentialId: "UC-c6aa0597-48c0-40e6-8806-5b0d03076b9f"
      }
    ]
  },
  {
    name: "Forage",
    emoji: "\u{1F3E2}",
    certificates: [
      {
        title: "Accenture North America - Data Analytics and Visualization Job Simulation",
        issuer: "Forage",
        date: "Apr 2025",
        credentialId: "DoMGm6hnmdWE4cJm2",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/T6kdcdKSTfg2aotxT/hzmoNKtzvAzXsEqx8_T6kdcdKSTfg2aotxT_EGf2NRH3awR8np98E_1745820481470_completion_certificate.pdf"
      },
      {
        title: "British Airways - Data Science Job Simulation",
        issuer: "Forage",
        date: "Apr 2025",
        credentialId: "CxDg8Dcba8mk9KZxm",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/tMjbs76F526fF5v3G/NjynCWzGSaWXQCxSX_tMjbs76F526fF5v3G_EGf2NRH3awR8np98E_1745654050121_completion_certificate.pdf"
      },
      {
        title: "Commonwealth Bank - Introduction to Data Science Job Simulation",
        issuer: "Forage",
        date: "Mar 2025",
        credentialId: "D8T9bN4FNCMwwSZr5",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/2sNmYuurxgpFYawco/smwfytX3mcLboA9bf_2sNmYuurxgpFYawco_EGf2NRH3awR8np98E_1741418522339_completion_certificate.pdf"
      },
      {
        title: "PwC Switzerland - Power BI Job Simulation",
        issuer: "Forage",
        date: "Mar 2025",
        credentialId: "CQ6Z2m9jAD9MzRQRN",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/4sLyCPgmsy8DA6Dh3/a87GpgE6tiku7q3gu_4sLyCPgmsy8DA6Dh3_EGf2NRH3awR8np98E_1741416915258_completion_certificate.pdf"
      },
      {
        title: "BCG - GenAI Job Simulation",
        issuer: "Forage",
        date: "Mar 2025",
        credentialId: "PLaRTiPksTD6Fzaj7",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/SKZxezskWgmFjRvj9/gabev3vXhuACr48eb_SKZxezskWgmFjRvj9_EGf2NRH3awR8np98E_1741367264649_completion_certificate.pdf"
      },
      {
        title: "Deloitte Australia - Data Analytics Job Simulation",
        issuer: "Forage",
        date: "Feb 2025",
        credentialId: "is2c5RTXemSGLiM8i",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqmSxAf6zZTseP_EGf2NRH3awR8np98E_1740745445233_completion_certificate.pdf"
      },
      {
        title: "Quantium - Data Analytics Job Simulation",
        issuer: "Forage",
        date: "Feb 2025",
        credentialId: "YAmG3EksB3yrLYeM3",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/32A6DqtsbF7LbKdcq/NkaC7knWtjSbi6aYv_32A6DqtsbF7LbKdcq_EGf2NRH3awR8np98E_1740744438208_completion_certificate.pdf"
      },
      {
        title: "Tata Group - Data Visualisation: Empowering Business with Effective Insights Job Simulation",
        issuer: "Forage",
        date: "Feb 2025",
        credentialId: "9WwyTogudp8uwtb7L",
        url: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ifobHAoMjQs9s6bKS/MyXvBcppsW2FkNYCX_ifobHAoMjQs9s6bKS_EGf2NRH3awR8np98E_1739298219504_completion_certificate.pdf"
      }
    ]
  },
  {
    name: "Academic",
    emoji: "\u{1F393}",
    certificates: [
      {
        title: "Intelligent Mobility: Applied Computer Vision and Deep Learning",
        issuer: "SSN College of Engineering",
        date: "Jan 2022",
        credentialId: ""
      },
      {
        title: "Computer Graphics",
        issuer: "NPTEL",
        date: "Dec 2020",
        credentialId: ""
      },
      {
        title: "Programming in Java",
        issuer: "NPTEL",
        date: "Nov 2021",
        credentialId: ""
      },
      {
        title: "Mastering Data Structures & Algorithms using C and C++",
        issuer: "Udemy",
        date: "Dec 2023",
        credentialId: ""
      }
    ]
  },
  {
    name: "Non-Academic",
    emoji: "\u{1F3A8}",
    certificates: [
      {
        title: "The Complete Adobe After Effects Bootcamp: Basic to Advanced",
        issuer: "Udemy",
        date: "May 2023",
        credentialId: ""
      }
    ]
  }
];

// src/lib/mcp/tools/list-certificates.ts
var list_certificates_default = defineTool4({
  name: "list_certificates",
  title: "List certifications",
  description: "List Krithik's certifications grouped by category (Data Analytics, AI, Forage, Academic, Non-Academic), with issuer, date and verification link when available.",
  inputSchema: {
    category: z3.string().optional().describe("Optional category name filter, e.g. 'Forage'."),
    issuer: z3.string().optional().describe("Optional issuer filter, e.g. 'Udemy'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, issuer }) => {
    const cat = category?.trim().toLowerCase();
    const iss = issuer?.trim().toLowerCase();
    const result = certificateCategoriesInfo.filter((c) => !cat || c.name.toLowerCase().includes(cat)).map((c) => ({
      category: c.name,
      certificates: c.certificates.filter((cert) => !iss || cert.issuer.toLowerCase().includes(iss))
    })).filter((c) => c.certificates.length > 0);
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { categories: result }
    };
  }
});

// src/lib/mcp/tools/list-volunteering.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/data/volunteeringData.ts
var volunteeringData = [
  {
    role: "Academic Support Volunteer",
    company: "IntoUniversity",
    duration: "December 2025 - Present",
    description: "Tutoring Secondary school children in Science and Math, providing guidance on University selection.",
    achievements: []
  },
  {
    role: "Self-Organized Volunteer Educator for Government School Rural children",
    company: "Independent Initiative",
    duration: "November 2024 - August 2025",
    description: "Teaching 10-15 students from Classes 6 to 10 from local government schools as a personal initiative to give back.",
    achievements: [
      "Covering subjects like Math, Science, Computer Basics, and English, using relatable examples and interactive methods.",
      "Encouraging problem-solving, curiosity, and critical thinking among students.",
      "Mentoring them on spoken English, communication, and confidence-building.",
      "Making education more fun, inclusive, and approachable, especially for students with limited access to resources.",
      "A small effort to bridge learning gaps and spark interest in STEM and language skills alike."
    ]
  },
  {
    role: "Volunteer Educator & Animal Welfare Advocate",
    company: "InAmigos Foundation",
    duration: "February 2024 - March 2024",
    description: "Contributed to education and animal welfare initiatives through online teaching and community service.",
    achievements: [
      "Teaching 10+ children through online platforms like gmeet and zoom.",
      "Feeding stray animals and arranging for vaccinations.",
      "Collected and Recycled nearly 50kg+ of plastics."
    ]
  },
  {
    role: "Active Volunteer & Event Organizer",
    company: "SSN YRC",
    duration: "June 2019 - July 2021",
    description: "Actively participated in initiatives that significantly contribute to our community's well-being.",
    achievements: [
      "Played a pivotal role in successfully coordinating Blood Donation Camps, dedicating efforts to supporting crucial causes and making a tangible difference in the lives of those in need.",
      "Contributed voluntarily to Village Help Camps, collaborating with others to address the needs of underserved communities, fostering positive change and leaving a lasting impact on lives.",
      "Actively participated in environmental conservation through Lake Cleaning Rallies and Beach Cleaning Rallies, deepening conviction in the transformative power of collective action for positive and sustainable impacts on our surroundings."
    ]
  },
  {
    role: "Chief Video Editor",
    company: "TEDxYouth@Vannarpettai",
    duration: "May 2020 - April 2021",
    description: "Led video production and editing for one of South Tamil Nadu's first TEDx events.",
    companyLink: "https://www.instagram.com/tedxyouthvannarpettai/?hl=en",
    achievements: [
      "Edited all event videos (talks, promos, sponsor reels), ensuring alignment with TEDx brand standards.",
      "Coordinated with 6+ speakers and team members to collect and finalize video content.",
      "Managed sponsor video integration and communication, securing high-quality ad placements.",
      "Organized and executed end-to-end live streaming on BigBlueButton for a smooth virtual event.",
      "Created social media clips and highlight reels, boosting local engagement and awareness.",
      "Provided real-time technical support during the event, minimizing disruptions.",
      "Played a key role in launching one of South Tamil Nadu's first TEDx events, earning TED approval."
    ]
  }
];

// src/lib/mcp/tools/list-volunteering.ts
var list_volunteering_default = defineTool5({
  name: "list_volunteering",
  title: "List volunteering",
  description: "List Krithik's volunteering roles with organisation, duration and contributions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(volunteeringData, null, 2) }],
    structuredContent: { volunteering: volunteeringData }
  })
});

// src/lib/mcp/tools/list-education.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var education = [
  {
    institution: "The University of Leeds",
    location: "Leeds, England",
    degree: "Master of Science in Data Science and Analytics",
    duration: "September 2025 - Present",
    grade: "In Progress",
    coreModules: [
      "Data Science",
      "Learning Skills through Case Studies",
      "Dissertation in Data Science and Analytics"
    ],
    electiveModules: [
      "Machine Learning",
      "Programming for Data Science",
      "Big Data and Consumer Analytics",
      "Statistical Learning",
      "Statistical Theory and Methods",
      "Business Analytics and Decision Science"
    ]
  },
  {
    institution: "SSN College of Engineering",
    location: "Chennai, Tamil Nadu",
    degree: "Bachelor of Technology in Information Technology",
    duration: "2018 - 2022",
    grade: "GPA: 8.2",
    coreModules: [
      "Problem Solving and Programming in Python",
      "Database Management Systems and Applications",
      "Advanced Data Structures",
      "Artificial Intelligence Concepts and Algorithms",
      "Big Data Engineering",
      "Machine Learning Fundamentals"
    ],
    electiveModules: [
      "Fundamentals of Digital Image Processing",
      "Real Time Embedded Systems",
      "Reactive Programming",
      "Introduction to Deep Learning",
      "Programming in Java",
      "Professional Ethics"
    ]
  },
  {
    institution: "Pushpalatha Vidya Mandir",
    location: "Tirunelveli, Tamil Nadu",
    degree: "Senior Secondary Education (CBSE)",
    duration: "Grades 11 & 12",
    grade: "95.4%"
  },
  {
    institution: "Pushpalatha Vidya Mandir",
    location: "Tirunelveli, Tamil Nadu",
    degree: "Secondary Level of Education (CBSE)",
    duration: "Grades 9 & 10",
    grade: "CGPA: 10"
  }
];
var list_education_default = defineTool6({
  name: "list_education",
  title: "List education",
  description: "List Krithik's education history with degrees, institutions, grades and modules.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(education, null, 2) }],
    structuredContent: { education }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "krithik-sharan-portfolio",
  title: "Krithik Sharan Portfolio",
  version: "0.1.0",
  instructions: "Public read-only tools for Krithik Sharan S A's portfolio. Use `get_profile` for a summary and contact links, `list_experience` for work history, `list_projects` for portfolio and hackathon projects, `list_certificates` for certifications, `list_education` for degrees, and `list_volunteering` for volunteering work.",
  tools: [
    get_profile_default,
    list_experience_default,
    list_projects_default,
    list_certificates_default,
    list_volunteering_default,
    list_education_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
